export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';

export const PAGINATE_BOOK_SUCCESS = 'PAGINATE_BOOK_SUCCESS';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';