export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const PAGINATE_BOOKS_SUCCESS = 'PAGINATE_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'LOAD_BOOKS_FAILURE';
export const LOAD_BOOKS = 'LOAD_BOOKS';
